#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

$HOME/.config/polybar/launch.sh
picom --experimental-backends -b &
nitrogen --restore &

bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color \#8686ff

bspc config ignore_ewmh_focus true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Brave-browser desktop='^1' focus=off
bspc rule -a Alacritty desktop='^2' focus=off


# example
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
