#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5 6 7

~/.config/polybar/launch.sh &
nm-applet &
nitrogen --restore &
picom --experimental-backends -b &

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true
bspc config focused_border_color \#4C7899

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# workspace 1
bspc rule -a  Brave-browser desktop='^1'
bspc rule -a  Firefox desktop='^1'
bspc rule -a  Google-chrome desktop='^1'

# workspace 2
bspc rule -a  Alacritty desktop='^2'
bspc rule -a  kitty desktop='^2'

# workspace 3
bspc rule -a  Code desktop='^3'
bspc rule -a  jetbrains-goland desktop='^3'
bspc rule -a  jetbrains-webstorm desktop='^3'
bspc rule -a  jetbrains-datagrip desktop='^3'
bspc rule -a  Gedit desktop='^3'

# workspace 4
bspc rule -a  Pavucontrol desktop='^4'
bspc rule -a  Clementine desktop='^4'
bspc rule -a  Spotify desktop='^4'

# workspace 5
bspc rule -a Pcmanfm desktop='^5'

# workspace 6
bspc rule -a libreoffice-startcenter desktop='^6'

# workspace 7
bspc rule -a  discord desktop='^7'
bspc rule -a  Microsoft Teams - Preview desktop='^7'
bspc rule -a  zoom desktop='^7'
