#!/bin/sh

dte() {
    printf " $(date +"%A, %d %b %Y")"
}

tme() {
    printf " $(date +"%T")"
}

bat() {
    echo " $(count=$(acpi -b | wc -l); sum=$(acpi -b | egrep -o '[0-9]{1,3}%' | tr -d '%' | xargs -I% echo -n '+%'); echo $(( sum / count ))%%)" 
}

cpu() {
    echo "ﮕ $(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%%"}')"
}

net() {
    echo "直 $(iwgetid -r)"
}

status() {
    printf " $(cpu) $(bat) $(net) $(tme) $(dte) "
}

while true; do
    xsetroot -name "$(status)"
    sleep .5s
done
