[colors.bright]
black = "#808080"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#FFFFFF"
yellow = "#feff00"

[colors.normal]
black = "#1e1e1e"
blue = "#569cd6"
cyan = "#9cdcfe"
green = "#608b4e"
magenta = "#c586c0"
red = "#f44747"
white = "#d4d4d4"
yellow = "#d7ba7d"

[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"

[font]
size = 10

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[72;6u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;6u"
key = "L"
mods = "Control|Shift"

[window]
decorations = "none"
dynamic_padding = false

[window.padding]
x = 5
y = 5
